project_name: rustdesk-api-server
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
checksum:
  name_template: 'checksums.txt'
archives:
  - replacements:
      linux: Linux
      windows: Windows
      darwin: MacOs
      386: i386
      amd64: x86_64
    files:
      - README.md
      - img.png
      - dist/*
      - conf/app.conf
