project_name: rustdesk-api-server
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - id: default
    builds:
      - default
    format_overrides:
      - goos: windows
        format: zip
    files:
      - conf/app.conf
